import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.scss';
import Layout from 'src/Layout/Layout';
import { Open_Sans } from 'next/font/google';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import 'aos/dist/aos.css';

export const fontOpenSans = Open_Sans({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${fontOpenSans.className}`}>
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
